"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lon+y2c9s+$=-pb!f@tlqq=@t+3%g8!^4v-+pnwq2pq1076nz+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Unfold must be first!
    'unfold',
    
    # Default Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Baptist ICT Core Apps
    'core',
    'accounts',
    'courses',
    'enrollments',
    'finance',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Tell Django to use our custom role-based User model
AUTH_USER_MODEL = 'accounts.User'

from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _


def _sidebar_finance_permission(request):
    """
    Only Finance Officers and Super Admins should see the Finance section.
    """
    user = request.user
    if not getattr(user, "is_authenticated", False):
        return False

    groups = set(user.groups.values_list("name", flat=True))
    role = getattr(user, "role", None)

    if user.is_superuser or "Super Admin" in groups:
        return True

    if "Finance" in groups:
        return True

    try:
        from accounts.models import User as AccountsUser  # local import to avoid cycles

        return role == AccountsUser.RoleChoices.FINANCE
    except Exception:
        # Fall back to a conservative default if models are not ready.
        return False


def _sidebar_system_permission(request):
    """
    System configuration should be visible only to technical admins / super admins.
    """
    user = request.user
    if not getattr(user, "is_authenticated", False):
        return False

    groups = set(user.groups.values_list("name", flat=True))
    if user.is_superuser or "Super Admin" in groups or "IT Admin" in groups:
        return True

    return False


def _sidebar_registrar_permission(request):
    """
    Registrar should only see enrollment-related sections, not course/batch management.
    """
    user = request.user
    if not getattr(user, "is_authenticated", False):
        return False

    groups = set(user.groups.values_list("name", flat=True))
    return "Registrar" in groups or "Admissions" in groups


def _sidebar_it_admin_permission(request):
    """
    IT Admin should see courses, batches, and user management.
    """
    user = request.user
    if not getattr(user, "is_authenticated", False):
        return False

    groups = set(user.groups.values_list("name", flat=True))
    if user.is_superuser or "Super Admin" in groups or "IT Admin" in groups:
        return True

    try:
        from accounts.models import User as AccountsUser
        return getattr(user, "role", None) == AccountsUser.RoleChoices.IT_ADMIN
    except Exception:
        return False


# Unfold Theme Configuration
UNFOLD = {
    "SITE_TITLE": "Baptist ICT ERP",
    "SITE_HEADER": "Baptist ICT Command Center",
    "SITE_URL": "/",
    "DASHBOARD_CALLBACK": "core.views.dashboard_callback",
    "COLORS": {
        "primary": {
            "50": "#eff6ff",
            "100": "#dbeafe",
            "200": "#bfdbfe",
            "300": "#93c5fd",
            "400": "#60a5fa",
            "500": "#3b82f6",  # Academic Blue
            "600": "#2563eb",
            "700": "#1d4ed8",
            "800": "#1e40af",
            "900": "#1e3a8a",
            "950": "#172554",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "command_search": False,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Overview"),
                "separator": False,
                "collapsible": False,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": _("Accounts"),
                "separator": True,
                "collapsible": True,
                "permission": _sidebar_it_admin_permission,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "people",
                        "link": reverse_lazy("admin:accounts_user_changelist"),
                    },
                ],
            },
            {
                "title": _("Academics"),
                "separator": False,
                "collapsible": True,
                "permission": _sidebar_it_admin_permission,
                "items": [
                    {
                        "title": _("Courses"),
                        "icon": "menu_book",
                        "link": reverse_lazy("admin:courses_course_changelist"),
                    },
                    {
                        "title": _("Batches"),
                        "icon": "class",
                        "link": reverse_lazy("admin:courses_batch_changelist"),
                    },
                ],
            },
            {
                "title": _("Enrollments"),
                "separator": False,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Enrollments"),
                        "icon": "how_to_reg",
                        "link": reverse_lazy(
                            "admin:enrollments_enrollment_changelist"
                        ),
                    },
                ],
            },
            {
                "title": _("Finance"),
                "separator": False,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Payments"),
                        "icon": "payments",
                        "link": reverse_lazy("admin:finance_payment_changelist"),
                        "permission": _sidebar_finance_permission,
                    },
                ],
            },
            {
                "title": _("System"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Groups & permissions"),
                        "icon": "admin_panel_settings",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                        "permission": _sidebar_system_permission,
                    },
                ],
            },
            {
                "title": _("Help"),
                "separator": False,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Staff guide"),
                        "icon": "help_center",
                        "link": "/docs/",
                    },
                ],
            },
        ],
    },
}
